# Generated by Django 4.1.4 on 2022-12-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
