# Generated by Django 4.1.4 on 2023-01-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("microblog_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
